// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFFDG9Xf1nTuFtPPPTcInrNJDMr0Yldg',
    appId: '1:315254596570:web:cfa4353cc16e4d59da16e3',
    messagingSenderId: '315254596570',
    projectId: 'jutcapp',
    authDomain: 'jutcapp.firebaseapp.com',
    storageBucket: 'jutcapp.appspot.com',
    measurementId: 'G-FWRRNXWJH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfk3xdSqeXlEALnsB-z2HdQojg4r7TD9w',
    appId: '1:315254596570:android:817fe985b3ec2bf5da16e3',
    messagingSenderId: '315254596570',
    projectId: 'jutcapp',
    storageBucket: 'jutcapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBp5wZZI9TKfGPLvv28QDJ5WKgZxHm1ZY',
    appId: '1:315254596570:ios:737a6115012077dcda16e3',
    messagingSenderId: '315254596570',
    projectId: 'jutcapp',
    storageBucket: 'jutcapp.appspot.com',
    iosBundleId: 'com.example.jutcapp',
  );
}
